T: .5
q1: .5
q2: 1e-1
s2: 1
nsim: 20
dynamic_filter_iterations: 10

model:
  _target_: ssmjax.examples.dynitertracking.build_model
  T: ${..T}
  q1: ${..q1}
  q2: ${..q2}
  s2: ${..s2}

propagate_first: False

initial_state:
  _target_: ssmjax.types.MVNormal
  mean:
    _target_: numpy.array
    object: [130, 35, -20, 20, -0.0698132] # -4*pi/180
  cov:
    _target_: numpy.diag
    v: [5, 5, 5, 5, 1e-2]

initial_theta:
  _target_: ssmjax.types.MVNormal
  mean:
    _target_: numpy.array
    object: [0.]

unscented_parameters: # UT w/ w0 = 1/3
  alpha: 0.7746
  beta: 2
  kappa: 7.5

data_generator:
  _partial_: True
  _target_: ssmjax.examples.dynitertracking.generate_data
  rkey:
    _target_: jax.random.PRNGKey
    seed: 13
  nsim: ${..nsim}
  model: ${..model}
  initial_state: ${..initial_state}
